<?php

use Illuminate\Database\Seeder;

class ProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = [
            [
                'name' => 'Bat',
                'detail' => '',
                'img' => 'bat.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Beaver',
                'detail' => '',
                'img' => 'beaver.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Bee',
                'detail' => '',
                'img' => 'bee.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Beetle',
                'detail' => '',
                'img' => 'beetle.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Bulldog',
                'detail' => '',
                'img' => 'bulldog.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Camel',
                'detail' => '',
                'img' => 'camel.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Canary',
                'detail' => '',
                'img' => 'canary.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Cat',
                'detail' => '',
                'img' => 'cat.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Chameleon',
                'detail' => '',
                'img' => 'chameleon.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Chicken',
                'detail' => '',
                'img' => 'chicken.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Clown-Fish',
                'detail' => '',
                'img' => 'clown-fish.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Cobra',
                'detail' => '',
                'img' => 'cobra.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Cow',
                'detail' => '',
                'img' => 'cow.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Crab',
                'detail' => '',
                'img' => 'crab.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Crocodile',
                'detail' => '',
                'img' => 'crocodile.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Duck',
                'detail' => '',
                'img' => 'duck.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Elephant',
                'detail' => '',
                'img' => 'elephant.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Fox',
                'detail' => '',
                'img' => 'fox.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Frog',
                'detail' => '',
                'img' => 'frog.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Giraffe',
                'detail' => '',
                'img' => 'giraffe.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Hippopotamus',
                'detail' => '',
                'img' => 'hippopotamus.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Humming-Bird',
                'detail' => '',
                'img' => 'humming-bird.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Kangaroo',
                'detail' => '',
                'img' => 'kangaroo.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Lion',
                'detail' => '',
                'img' => 'lion.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Llama',
                'detail' => '',
                'img' => 'llama.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Macaw',
                'detail' => '',
                'img' => 'macaw.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Monkey',
                'detail' => '',
                'img' => 'monkey.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Moose',
                'detail' => '',
                'img' => 'moose.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Mouse',
                'detail' => '',
                'img' => 'mouse.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Octopus',
                'detail' => '',
                'img' => 'octopus.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Ostrich',
                'detail' => '',
                'img' => 'ostrich.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Owl',
                'detail' => '',
                'img' => 'owl.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Panda',
                'detail' => '',
                'img' => 'panda.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Pelican',
                'detail' => '',
                'img' => 'pelican.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Penguin',
                'detail' => '',
                'img' => 'penguin.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Pig',
                'detail' => '',
                'img' => 'pig.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Rabbit',
                'detail' => '',
                'img' => 'rabbit.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Racoon',
                'detail' => '',
                'img' => 'racoon.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Rhinoceros',
                'detail' => '',
                'img' => 'rhinoceros.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Shark',
                'detail' => '',
                'img' => 'shark.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Sheep',
                'detail' => '',
                'img' => 'sheep.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Siberian-Husky',
                'detail' => '',
                'img' => 'siberian-husky.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Sloth',
                'detail' => '',
                'img' => 'sloth.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Snake',
                'detail' => '',
                'img' => 'snake.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Squirrel',
                'detail' => '',
                'img' => 'squirrel.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Swan',
                'detail' => '',
                'img' => 'swan.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Tiger',
                'detail' => '',
                'img' => 'tiger.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Toucan',
                'detail' => '',
                'img' => 'toucan.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Turtle',
                'detail' => '',
                'img' => 'turtle.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Whale',
                'detail' => '',
                'img' => 'whale.png',
                'type_id' => 1,
                'created_at' => now(),
                ],
                [
                'name' => 'Apple',
                'detail' => '',
                'img' => 'apple.jpg',
                'type_id' => 2,
                'created_at' => now(),
                ],
                [
                'name' => 'Avocado',
                'detail' => '',
                'img' => 'avocado.jpg',
                'type_id' => 2,
                'created_at' => now(),
                ],
                [
                'name' => 'Banana',
                'detail' => '',
                'img' => 'banana.jpg',
                'type_id' => 2,
                'created_at' => now(),
                ],
                [
                'name' => 'Blackberry',
                'detail' => '',
                'img' => 'blackberry.jpg',
                'type_id' => 2,
                'created_at' => now(),
                ],
                [
                'name' => 'Cherry',
                'detail' => '',
                'img' => 'cherry.jpg',
                'type_id' => 2,
                'created_at' => now(),
                ],
                [
                'name' => 'Coconut',
                'detail' => '',
                'img' => 'coconut.jpg',
                'type_id' => 2,
                'created_at' => now(),
                ],
                [
                'name' => 'Corn',
                'detail' => '',
                'img' => 'corn.jpg',
                'type_id' => 2,
                'created_at' => now(),
                ],
                [
                'name' => 'Dragon-Fruit',
                'detail' => '',
                'img' => 'dragon-fruit.jpg',
                'type_id' => 2,
                'created_at' => now(),
                ],
                [
                'name' => 'Durian',
                'detail' => '',
                'img' => 'durian.jpg',
                'type_id' => 2,
                'created_at' => now(),
                ],
                [
                'name' => 'Fresh-Coconut',
                'detail' => '',
                'img' => 'fresh-coconut.jpg',
                'type_id' => 2,
                'created_at' => now(),
                ],
                [
                'name' => 'Grape',
                'detail' => '',
                'img' => 'grape.jpg',
                'type_id' => 2,
                'created_at' => now(),
                ],
                [
                'name' => 'Kiwi',
                'detail' => '',
                'img' => 'kiwi.jpg',
                'type_id' => 2,
                'created_at' => now(),
                ],
                [
                'name' => 'Lime',
                'detail' => '',
                'img' => 'lime.jpg',
                'type_id' => 2,
                'created_at' => now(),
                ],
                [
                'name' => 'Orange',
                'detail' => '',
                'img' => 'orange.jpg',
                'type_id' => 2,
                'created_at' => now(),
                ],
                [
                'name' => 'Peach',
                'detail' => '',
                'img' => 'peach.jpg',
                'type_id' => 2,
                'created_at' => now(),
                ],
                [
                'name' => 'Pineapple',
                'detail' => '',
                'img' => 'pineapple.jpg',
                'type_id' => 2,
                'created_at' => now(),
                ],
                [
                'name' => 'Pomegranate',
                'detail' => '',
                'img' => 'pomegranate.jpg',
                'type_id' => 2,
                'created_at' => now(),
                ],
                [
                'name' => 'Strawberry',
                'detail' => '',
                'img' => 'strawberry.jpg',
                'type_id' => 2,
                'created_at' => now(),
                ],

        ];
        DB::table('products')->insert($products);
    }
}
